name: Master workflow
on:
  push:
    branches:
      - master
jobs:
  minikube:
    name: minikube
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Cache minikube
        uses: actions/cache@v2
        with:
          path: |
            ~/.minikube/cache
            ~/.minikube/bin
          key: ${{ runner.os }}-minikube
      - name: Run in minikube
        run: |
          brew install minikube
          brew install hyperkit
          brew install docker
          minikube start --wait all
          eval $(minikube docker-env)
          docker build . -t testing
          docker container run testing
  docker-for-mac:
    name: Docker for Mac
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run in Docker for Mac
        run: |
          ./install-docker-for-mac.sh
          docker build . -t testing
          docker container run testing
  dummy:
    name: Dummy
    runs-on: macos-latest
    steps:
      - name: Dummy
        run: |
          brew --cache
